### ISSUE TITLE
Hi, it seems some APi has been changed

### ISSUE THREAD

**Issue by datle56** [thedtvn/MBBank#3]
mb.getTransactionAccountHistory(from_date=lasttime, to_date=daynow)
     67             else:
     68                 err_out = data_out["result"]
---> 69                 raise Exception(f"{err_out['responseCode']} | {err_out['message']}")
     70         return data_out
     71 

Exception: GW525 | Feature switch to new api

**Comment by thedtvn** [comment]
> mb.getTransactionAccountHistory(from_date=lasttime, to_date=daynow) 67 else: 68 err_out = data_out["result"] ---> 69 raise Exception(f"{err_out['responseCode']} | {err_out['message']}") 70 return data_out 71
> 
> Exception: GW525 | Feature switch to new api

@datle56 thank let me see and fix

**Comment by thedtvn** [comment]
@datle56 fixed [v0.1.0](https://github.com/thedtvn/MBBank/releases/tag/v0.1.0)
