### ISSUE TITLE
"Error GW266 | Device Invalid" keep session for next request

### ISSUE THREAD

**Issue by canhbd** [thedtvn/MBBank#8]
The first thank for your sharing,
I have a problem, I want to keep session id for next request.

(headers and payload of next request, that I still keep the same as the first request)

However, error "Error GW266 | Device Invalid" occured, how can I fix it?

Thank you!

**Comment by thedtvn** [comment]
@canhbd thanks for report let me check that error

**Comment by thedtvn** [comment]
@canhbd sory that you can not use session id for next req if it expired
